#' Import DADA2 Pipeline Outputs into tidy_microbiome
#'
#' @description
#' Ingests sequence table and taxonomy matrices generated by the DADA2 pipeline,
#' converting sample-by-sequence matrices into a synchronized `tidy_microbiome` container.
#' Optionally shortens long DNA sequence column names to clean identifiers (e.g. `ASV0001`)
#' while preserving full nucleotide sequences in the taxonomy table.
#'
#' @param seqtab A matrix, data frame, or path to an RDS/TSV file containing DADA2 sequence table
#'   (samples as rows, ASV sequences as columns).
#' @param taxa Optional matrix, data frame, or path to an RDS/TSV file containing taxonomy assignments
#'   (ASVs as rows, taxonomic ranks as columns).
#' @param sample_metadata Optional data frame or path to a TSV/CSV file containing sample metadata.
#' @param clean_names Logical. If `TRUE` (default), converts long nucleotide sequences into clean
#'   `ASV001`, `ASV002`... identifiers and preserves sequence strings in taxonomy column `sequence`.
#'
#' @return A `tidy_microbiome` object.
#' @export
import_dada2 <- function(seqtab,
                         taxa = NULL,
                         sample_metadata = NULL,
                         clean_names = TRUE) {
  # Load seqtab if path
  if (is.character(seqtab) && length(seqtab) == 1) {
    if (grepl("\\.rds$", seqtab, ignore.case = TRUE)) {
      seqtab <- readRDS(seqtab)
    } else {
      seqtab <- as.matrix(utils::read.table(seqtab, header = TRUE, row.names = 1, sep = "\t", check.names = FALSE))
    }
  }
  seqtab <- as.matrix(seqtab)

  # Load taxa if path
  if (!is.null(taxa) && is.character(taxa) && length(taxa) == 1) {
    if (grepl("\\.rds$", taxa, ignore.case = TRUE)) {
      taxa <- readRDS(taxa)
    } else {
      taxa <- as.matrix(utils::read.table(taxa, header = TRUE, row.names = 1, sep = "\t", check.names = FALSE))
    }
  }

  # Load sample metadata if path
  if (!is.null(sample_metadata) && is.character(sample_metadata) && length(sample_metadata) == 1) {
    if (grepl("\\.csv$", sample_metadata, ignore.case = TRUE)) {
      sample_metadata <- utils::read.csv(sample_metadata, stringsAsFactors = FALSE, check.names = FALSE)
    } else {
      sample_metadata <- utils::read.table(sample_metadata, header = TRUE, sep = "\t", stringsAsFactors = FALSE, check.names = FALSE)
    }
  }

  # DADA2 output has samples as rows and sequences as columns -> transpose to taxa x samples
  counts <- t(seqtab)
  sample_names <- colnames(counts)
  seq_names <- rownames(counts)
  n_taxa <- nrow(counts)

  ref_seqs <- seq_names
  if (clean_names && any(nchar(seq_names) > 20)) {
    id_format <- sprintf("ASV%%0%dd", ceiling(log10(n_taxa + 1)))
    new_ids <- sprintf(id_format, seq_len(n_taxa))
    rownames(counts) <- new_ids
    if (!is.null(taxa) && nrow(taxa) == n_taxa) {
      rownames(taxa) <- new_ids
    }
  } else {
    new_ids <- seq_names
  }

  # Build taxonomy table
  if (is.null(taxa)) {
    tax_df <- tibble::tibble(
      taxon_id = new_ids,
      sequence = ref_seqs
    )
  } else {
    tax_df <- tibble::as_tibble(as.data.frame(taxa), rownames = "taxon_id")
    if (clean_names && any(nchar(ref_seqs) > 20) && !"sequence" %in% colnames(tax_df)) {
      tax_df$sequence <- ref_seqs
    }
  }

  # Build sample metadata
  if (is.null(sample_metadata)) {
    sample_metadata <- tibble::tibble(sample_id = sample_names)
  } else {
    sample_metadata <- tibble::as_tibble(sample_metadata)
    if (!"sample_id" %in% colnames(sample_metadata)) {
      if (nrow(sample_metadata) == length(sample_names)) {
        sample_metadata <- tibble::add_column(sample_metadata, sample_id = sample_names, .before = 1)
      } else {
        stop("sample_metadata does not contain a 'sample_id' column.", call. = FALSE)
      }
    }
    # Reorder metadata to match count matrix
    m_idx <- match(sample_names, sample_metadata$sample_id)
    if (any(is.na(m_idx))) {
      stop("Some samples in seqtab are missing from sample_metadata.", call. = FALSE)
    }
    sample_metadata <- sample_metadata[m_idx, , drop = FALSE]
  }

  tidy_microbiome(
    counts = counts,
    sample_data = sample_metadata,
    tax_table = tax_df
  )
}

#' Import QIIME 2 Artifacts or TSV Tables
#'
#' @description
#' Constructs a `tidy_microbiome` container from QIIME 2 exported TSV files
#' (feature table, taxonomy TSV with semicolon delimiters, sample metadata, and optional tree).
#'
#' @param feature_table Matrix, data frame, or file path to QIIME 2 feature table (TSV).
#' @param taxonomy Optional file path or data frame to QIIME 2 taxonomy TSV (`Feature.ID`, `Taxon`, `Confidence`).
#' @param sample_metadata Optional file path or data frame containing sample metadata.
#' @param tree Optional file path to a Newick tree file (`tree.nwk`) or an `ape::phylo` object.
#'
#' @return A `tidy_microbiome` object.
#' @export
import_qiime2 <- function(feature_table,
                          taxonomy = NULL,
                          sample_metadata = NULL,
                          tree = NULL) {
  # Read feature table
  if (is.character(feature_table) && length(feature_table) == 1) {
    # Skip BIOM comment lines starting with '#'
    lines <- readLines(feature_table, n = 5)
    skip_n <- sum(grepl("^# Constructed from biom", lines))
    counts_df <- utils::read.table(feature_table, header = TRUE, sep = "\t",
                                   skip = skip_n, comment.char = "", check.names = FALSE,
                                   stringsAsFactors = FALSE)
    # Remove leading '#' from column name if present
    colnames(counts_df)[1] <- sub("^#", "", colnames(counts_df)[1])
    rownames(counts_df) <- counts_df[[1]]
    counts_mat <- as.matrix(counts_df[, -1, drop = FALSE])
  } else {
    counts_mat <- as.matrix(feature_table)
  }

  taxa_ids <- rownames(counts_mat)
  sample_ids <- colnames(counts_mat)

  # Parse taxonomy
  if (!is.null(taxonomy)) {
    if (is.character(taxonomy) && length(taxonomy) == 1) {
      tax_raw <- utils::read.table(taxonomy, header = TRUE, sep = "\t",
                                   comment.char = "", check.names = FALSE,
                                   stringsAsFactors = FALSE)
    } else {
      tax_raw <- as.data.frame(taxonomy)
    }
    colnames(tax_raw)[1:2] <- c("taxon_id", "Taxon")
    # Parse semicolon strings: k__Bacteria; p__Firmicutes; ...
    tax_split <- strsplit(as.character(tax_raw$Taxon), ";\\s*")
    standard_ranks <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")

    parsed_tax <- do.call(rbind, lapply(tax_split, function(ranks) {
      row <- rep(NA_character_, length(standard_ranks))
      for (r in ranks) {
        if (grepl("^[kpcofgs]__", r)) {
          prefix <- substr(r, 1, 3)
          val <- sub("^[kpcofgs]__", "", r)
          target_idx <- switch(
            prefix,
            "k__" = 1, "p__" = 2, "c__" = 3, "o__" = 4,
            "f__" = 5, "g__" = 6, "s__" = 7, NA_integer_
          )
          if (!is.na(target_idx)) row[target_idx] <- val
        }
      }
      row
    }))
    colnames(parsed_tax) <- standard_ranks
    tax_df <- tibble::as_tibble(cbind(taxon_id = tax_raw$taxon_id, as.data.frame(parsed_tax, stringsAsFactors = FALSE)))
    
    # Align to counts matrix
    m_idx <- match(taxa_ids, tax_df$taxon_id)
    tax_df <- tax_df[m_idx, , drop = FALSE]
  } else {
    tax_df <- tibble::tibble(taxon_id = taxa_ids)
  }

  # Sample metadata
  if (!is.null(sample_metadata)) {
    if (is.character(sample_metadata) && length(sample_metadata) == 1) {
      sample_df <- utils::read.table(sample_metadata, header = TRUE, sep = "\t",
                                     comment.char = "", check.names = FALSE,
                                     stringsAsFactors = FALSE)
      # Skip QIIME 2 q2:type row if present
      if (nrow(sample_df) > 0 && grepl("^#q2:", sample_df[1, 1])) {
        sample_df <- sample_df[-1, , drop = FALSE]
      }
    } else {
      sample_df <- as.data.frame(sample_metadata)
    }
    colnames(sample_df)[1] <- "sample_id"
    sample_df <- tibble::as_tibble(sample_df)
    m_s <- match(sample_ids, sample_df$sample_id)
    if (any(is.na(m_s))) {
      sample_df <- tibble::tibble(sample_id = sample_ids)
    } else {
      sample_df <- sample_df[m_s, , drop = FALSE]
    }
  } else {
    sample_df <- tibble::tibble(sample_id = sample_ids)
  }

  # Tree
  phy_tree <- NULL
  if (!is.null(tree)) {
    if (is.character(tree) && length(tree) == 1 && file.exists(tree) && requireNamespace("ape", quietly = TRUE)) {
      phy_tree <- ape::read.tree(tree)
    } else if (inherits(tree, "phylo")) {
      phy_tree <- tree
    }
  }

  tb <- tidy_microbiome(
    counts = counts_mat,
    sample_data = sample_df,
    tax_table = tax_df,
    phy_tree = phy_tree
  )
  tb
}

#' Import MetaPhlAn Taxonomic Profiles
#'
#' @description
#' Parses MetaPhlAn (version 3 or 4) merged abundance profile tables containing
#' hierarchical clade strings (`k__...|p__...|s__...`) and relative abundances.
#'
#' @param file Path to MetaPhlAn merged abundance TSV file.
#' @param rank Taxonomic rank to extract (e.g. `"Species"`, `"Genus"`, or `"all"`). Defaults to `"Species"`.
#' @param sample_metadata Optional data frame or TSV file path containing sample metadata.
#'
#' @return A `tidy_microbiome` object with relative abundance stored in assay `"relabundance"` and `"counts"`.
#' @export
import_metaphlan <- function(file, rank = "Species", sample_metadata = NULL) {
  if (!file.exists(file)) {
    stop(sprintf("File '%s' does not exist.", file), call. = FALSE)
  }

  raw_df <- utils::read.table(file, header = TRUE, sep = "\t",
                              comment.char = "", check.names = FALSE,
                              stringsAsFactors = FALSE)

  clade_col <- colnames(raw_df)[1]
  clades <- as.character(raw_df[[clade_col]])

  rank_prefix <- switch(
    rank,
    Kingdom = "k__",
    Phylum  = "p__",
    Class   = "c__",
    Order   = "o__",
    Family  = "f__",
    Genus   = "g__",
    Species = "s__",
    "s__"
  )

  # Filter clades matching the specified rank at the terminal node
  if (rank != "all") {
    keep_idx <- grepl(paste0(rank_prefix, "[^|]+$"), clades)
    if (sum(keep_idx) == 0) {
      keep_idx <- seq_along(clades)
    }
  } else {
    keep_idx <- seq_along(clades)
  }

  sub_df <- raw_df[keep_idx, , drop = FALSE]
  target_clades <- as.character(sub_df[[clade_col]])

  # Parse taxonomic ranks
  standard_ranks <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")
  tax_mat <- do.call(rbind, lapply(target_clades, function(clade) {
    parts <- strsplit(clade, "\\|")[[1]]
    res <- rep(NA_character_, 7)
    for (p in parts) {
      prefix <- substr(p, 1, 3)
      val <- sub("^[kpcofgs]__", "", p)
      idx <- switch(
        prefix,
        "k__" = 1, "p__" = 2, "c__" = 3, "o__" = 4,
        "f__" = 5, "g__" = 6, "s__" = 7, NA_integer_
      )
      if (!is.na(idx)) res[idx] <- val
    }
    res
  }))
  colnames(tax_mat) <- standard_ranks

  # ASV/Taxon ID from terminal rank or clade
  terminal_names <- sapply(strsplit(target_clades, "\\|"), function(p) utils::tail(p, 1))
  terminal_names <- sub("^[kpcofgs]__", "", terminal_names)

  tax_df <- tibble::as_tibble(cbind(taxon_id = terminal_names, as.data.frame(tax_mat, stringsAsFactors = FALSE)))

  # Numeric abundance matrix
  num_cols <- which(sapply(sub_df, is.numeric))
  counts_mat <- as.matrix(sub_df[, num_cols, drop = FALSE])
  rownames(counts_mat) <- terminal_names
  sample_names <- colnames(counts_mat)

  # Sample metadata
  if (!is.null(sample_metadata)) {
    if (is.character(sample_metadata) && length(sample_metadata) == 1) {
      sample_df <- utils::read.table(sample_metadata, header = TRUE, sep = "\t",
                                     comment.char = "", check.names = FALSE,
                                     stringsAsFactors = FALSE)
    } else {
      sample_df <- as.data.frame(sample_metadata)
    }
    colnames(sample_df)[1] <- "sample_id"
    sample_df <- tibble::as_tibble(sample_df)
    m_s <- match(sample_names, sample_df$sample_id)
    if (!any(is.na(m_s))) {
      sample_df <- sample_df[m_s, , drop = FALSE]
    } else {
      sample_df <- tibble::tibble(sample_id = sample_names)
    }
  } else {
    sample_df <- tibble::tibble(sample_id = sample_names)
  }

  tb <- tidy_microbiome(
    counts = counts_mat,
    sample_data = sample_df,
    tax_table = tax_df
  )
  attr(tb, "assays")[["relabundance"]] <- counts_mat
  tb
}
