# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
name: pkgdown

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only run on main/master branch of the upstream repository
    if: github.repository_owner == 'mladen5000'
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: |
          if (dir.exists("docs")) pkgdown::clean_site(force = TRUE)
          pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          branch: gh-pages
          folder: docs
